name: Test

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libudev-dev build-essential desktop-file-utils wget unzip zlib1g-dev liblzma-dev libssl-dev git imagemagick file libfuse2 clang xvfb qtbase5-dev

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Setup venv and install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        xvfb-run -a pytest -v src/main/python/test
